spring:
  profiles:
    active: @project.profile@
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: peach-auth-swagger
          uri: lb://peach-auth
          predicates:
            - Path=/api/auth/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: peach-monitor-swagger
          uri: lb://peach-monitor
          predicates:
            - Path=/api/monitor/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: peach-fileservice-swagger
          uri: lb://peach-fileservice
          predicates:
            - Path=/api/file/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: peach-setting-swagger
          uri: lb://peach-setting
          predicates:
            - Path=/api/setting/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: peach-message-swagger
          uri: lb://peach-message
          predicates:
            - Path=/api/message/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: peach-generator-swagger
          uri: lb://peach-generator
          predicates:
            - Path=/api/generator/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
        - id: peach-auth
          uri: lb://peach-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: peach-monitor
          uri: lb://peach-monitor
          predicates:
            - Path=/api/monitor/**
          filters:
            - StripPrefix=1
        - id: peach-fileservice
          uri: lb://peach-fileservice
          predicates:
            - Path=/api/file/**
          filters:
            - StripPrefix=1
        - id: peach-setting
          uri: lb://peach-setting
          predicates:
            - Path=/api/setting/**
          filters:
            - StripPrefix=1
        - id: peach-message-ws
          uri: lb:ws://peach-message
          predicates:
            - Path=/webSocket/**
        - id: peach-message
          uri: lb://peach-message
          predicates:
            - Path=/api/message/**
          filters:
            - StripPrefix=1
        - id: peach-generator
          uri: lb://peach-generator
          predicates:
            - Path=/api/generator/**
          filters:
            - StripPrefix=1

server:
  port: ${SERVER_PORT:18080}

knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: auth
        url: /api/auth/v3/api-docs
        service-name: peach-auth
        context-path: /api
        order: 1
      - name: monitor
        url: /api/monitor/v3/api-docs
        service-name: peach-monitor
        context-path: /api
        order: 2
      - name: fileservice
        url: /api/file/v3/api-docs
        service-name: peach-fileservice
        context-path: /api
        order: 3
      - name: message
        url: /api/message/v3/api-docs
        service-name: peach-message
        context-path: /api
        order: 4
      - name: setting
        url: /api/setting/v3/api-docs
        service-name: peach-setting
        context-path: /api
        order: 5
      - name: generator
        url: /api/generator/v3/api-docs
        service-name: peach-generator
        context-path: /api
        order: 6
