<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.peach</groupId>
    <artifactId>peach-userservice</artifactId>
    <name>peach-userservice</name>
    <description>peach-userservice</description>

    <parent>
        <groupId>com.peach</groupId>
        <artifactId>peach-cloud</artifactId>
        <version>${revision}</version>
    </parent>

    <packaging>pom</packaging>

    <modules>
        <module>peach-userservice-service</module>
        <module>peach-userservice-rest</module>
        <module>peach-userservice-launch</module>
        <module>peach-userservice-common</module>
        <module>peach-userservice-entity</module>
        <module>peach-userservice-rest-external</module>

    </modules>

</project>
