<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.peach</groupId>
    <artifactId>peach-satoken</artifactId>
    <name>peach-satoken</name>
    <description>peach-satoken</description>
    <packaging>pom</packaging>

    <parent>
        <groupId>com.peach</groupId>
        <artifactId>peach-middleware</artifactId>
        <version>${revision}</version>
    </parent>

    <modules>
        <module>peach-satoken-core</module>
        <module>peach-satoken-web-autoconfigure</module>
        <module>peach-satoken-web-starter</module>
        <module>peach-satoken-gateway-autoconfigure</module>
        <module>peach-satoken-gateway-starter</module>
    </modules>


</project>
