FROM nginx:1.25-alpine

ARG IMAGE_TITLE=Peach Front
ARG IMAGE_DESCRIPTION=Peach Cloud frontend
ARG IMAGE_AUTHORS="Mr Shu"
ARG IMAGE_VENDOR="Peach Cloud"
ARG IMAGE_VERSION="latest"

LABEL org.opencontainers.image.title="${IMAGE_TITLE}" \
      org.opencontainers.image.description="${IMAGE_DESCRIPTION}" \
      org.opencontainers.image.authors="${IMAGE_AUTHORS}" \
      org.opencontainers.image.vendor="${IMAGE_VENDOR}" \
      org.opencontainers.image.version="${IMAGE_VERSION}"

COPY nginx/peach.conf.template /etc/nginx/templates/default.conf.template
COPY runtime/build/front-dist/ /usr/share/nginx/html/
