peach:
  virtual-thread:
    enabled: true
    thread-name-prefix: peach-vt-
    shutdown-await: 30s
    groups:
      database:
        max-concurrency: 50
        max-pending: 100
        backpressure: BLOCK
        acquire-timeout: 50ms
      storage:
        max-concurrency: 50
        max-pending: 100
        backpressure: BLOCK
        acquire-timeout: 200ms
      remote:
        max-concurrency: 100
        max-pending: 200
        backpressure: BLOCK
        acquire-timeout: 100ms
