spring:
  application:
    name: peach-code-quickstart
  main:
    web-application-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

peach:
  code:
    enabled: true
    redis-enabled: false
    redis-key-prefix: "peach:code:generate:"

quickstart:
  code:
    demo:
      enabled: true
