<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.peach</groupId>
    <artifactId>peach-scheduler-starter</artifactId>
    <name>peach-scheduler-starter</name>
    <description>Peach distributed scheduler executor starter</description>
    <packaging>jar</packaging>

    <parent>
        <groupId>com.peach</groupId>
        <artifactId>peach-scheduler</artifactId>
        <version>${revision}</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>com.peach</groupId>
            <artifactId>peach-scheduler-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.peach</groupId>
            <artifactId>peach-scheduler-transport-rocket</artifactId>
        </dependency>
    </dependencies>
</project>
