spring:
  application:
    name: peach-redission-distributedlock-quickstart
  main:
    web-application-type: none

peach:
  redis:
    mode: standalone
    host: ${PEACH_REDIS_HOST:127.0.0.1:6379}
    password: ${PEACH_REDIS_PASSWORD:}
    database: 0

quickstart:
  distributedlock:
    demo:
      enabled: true
