server:
  port: 18085

peach:
  multicache:
    enabled: true

springdoc:
  servers:
    - url: /api/setting
      description: Gateway
  packages-to-scan:
    - com.peach.setting.rest.internal
    - com.peach.setting.launch.health
