server:
  port: 18084

spring:
  main:
    web-application-type: reactive

springdoc:
  servers:
    - url: /api/message
      description: Gateway
  packages-to-scan:
    - com.peach.message.rest.internal
    - com.peach.message.launch.health

logging:
  level:
    com.alibaba.nacos: DEBUG
    com.alibaba.cloud.nacos: DEBUG
    org.springframework.cloud.bootstrap: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.gateway: DEBUG
