server:
  port: 18086

springdoc:
  servers:
    - url: /api/generator
      description: Gateway
  packages-to-scan:
    - com.peach.generator.rest.internal
    - com.peach.generator.launch.health
peach:
  openapi:
    version: V1.0.0
    server-url: /api/generator
    server-description: Gateway
