# 存储相关配置
peach.storage:
  enabled: true
  primary: aliyun
  providers:
    local:
      type: LOCAL
      bucket-name: peach-example
      root-path: ./data/peach-storage
      prefix: example/app
      domain: http://localhost/files
    aliyun:
      type: OSS
      name: aliyun
      endpoint: oss-cn-beijing.aliyuncs.com
      bucketName: peachsoft
      accessKey: "@OSS_ACCESS_KEY@"
      secretKey: "@OSS_SECRET_KEY@"
      region: cn-beijing
    cos:
      type: COS
      name: cos
      endpoint: cos.ap-beijing.myqcloud.com
      bucketName: peachsoft-1305539175
      accessKey: "@COS_ACCESS_KEY@"
      secretKey: "@COS_SECRET_KEY@"
      prefix: /cos/peach
      region: ap-beijing
    bos:
      type: BOS
      name: BOS
      endpoint: bj.bcebos.com
      bucketName: peachsoft
      accessKey: "@BOS_ACCESS_KEY@"
      secretKey: "@BOS_SECRET_KEY@"
      prefix: /bos/peach
      region: cn-beijing
    obs:
      type: OBS
      name: OBS
      endpoint: obs.myhuaweicloud.com
      bucketName: peachsoft
      accessKey: "@OBS_ACCESS_KEY@"
      secretKey: "@OBS_SECRET_KEY@"
      prefix: /obs/peach
      region: cn-beijing
