spring:
  application:
    name: peach-redis-tool-quickstart
  main:
    web-application-type: none

peach:
  redis:
    mode: standalone
    host: ${PEACH_REDIS_HOST:127.0.0.1:6379}
    password: ${PEACH_REDIS_PASSWORD:}
    database: 1

quickstart:
  redis-tool:
    demo:
      enabled: true
