CREATE TABLE mq_outbox_event (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    message_id VARCHAR(64) NOT NULL COMMENT 'starter 生成的消息 ID',
    topic VARCHAR(128) NOT NULL COMMENT 'RocketMQ topic',
    tag VARCHAR(128) DEFAULT NULL COMMENT 'RocketMQ tag',
    business_key VARCHAR(128) DEFAULT NULL COMMENT '业务 key',
    payload LONGTEXT NOT NULL COMMENT 'Base64 编码后的标准消息 Envelope',
    send_mode VARCHAR(32) NOT NULL COMMENT '发送模式：NORMAL、ORDERLY、DELAY',
    sharding_key VARCHAR(128) DEFAULT NULL COMMENT '顺序消息分片键',
    delay_level INT DEFAULT NULL COMMENT 'RocketMQ delay level',
    payload_type VARCHAR(256) DEFAULT NULL COMMENT 'payload 类型名称',
    headers TEXT DEFAULT NULL COMMENT '消息 headers 快照，仅用于排障和重放审计',
    status VARCHAR(32) NOT NULL COMMENT '状态：INIT、SENDING、SENT、RETRY、FAILED',
    retry_count INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    next_retry_time DATETIME NOT NULL COMMENT '下一次可重试时间',
    last_error VARCHAR(1000) DEFAULT NULL COMMENT '最近一次失败原因，禁止写入敏感明文',
    broker_message_id VARCHAR(128) DEFAULT NULL COMMENT 'RocketMQ Broker 返回的消息 ID',
    claimed_by VARCHAR(128) DEFAULT NULL COMMENT '抢占当前消息的调度器实例标识',
    claimed_at DATETIME DEFAULT NULL COMMENT '当前消息被抢占的时间',
    sent_at DATETIME DEFAULT NULL COMMENT '成功投递到 RocketMQ 的时间',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME NOT NULL COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_message_id (message_id),
    KEY idx_status_retry (status, next_retry_time),
    KEY idx_status_claimed (status, claimed_at),
    KEY idx_topic_key (topic, business_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='MQ Outbox 可靠消息表';
