<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.peach</groupId>
    <artifactId>peach-message-openfeign-external</artifactId>
    <name>peach-message-openfeign-external</name>
    <description>peach-message-openfeign-external</description>
    <packaging>jar</packaging>

    <parent>
        <groupId>com.peach</groupId>
        <artifactId>peach-message</artifactId>
        <version>${revision}</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>com.peach</groupId>
            <artifactId>peach-message-entity</artifactId>
        </dependency>

        <dependency>
            <groupId>com.peach</groupId>
            <artifactId>peach-openfeign-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
    </dependencies>
</project>
