<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.peach</groupId>
    <artifactId>peach-fileservice</artifactId>
    <name>peach-fileservice</name>
    <description>peach-fileservice</description>

    <parent>
        <groupId>com.peach</groupId>
        <artifactId>peach-cloud</artifactId>
        <version>${revision}</version>
    </parent>

    <packaging>pom</packaging>


    <modules>
        <module>peach-fileservice-service</module>
        <module>peach-fileservice-launch</module>
        <module>peach-fileservice-entity</module>
        <module>peach-fileservice-rest</module>
        <module>peach-fileservice-common</module>
        <module>peach-fileservice-openfeign-external</module>
    </modules>

</project>
