-- RocketMQ JDBC 消费幂等记录表（peach-scheduler-transport-rocket）

CREATE TABLE MQ_CONSUME_RECORD
(
    ID              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
    IDEMPOTENT_KEY  VARCHAR(256) NOT NULL COMMENT '幂等键',
    CONSUMER_GROUP  VARCHAR(128) NOT NULL COMMENT '消费者组',
    TOPIC           VARCHAR(128) NULL COMMENT 'RocketMQ Topic',
    TAG             VARCHAR(128) NULL COMMENT 'RocketMQ Tag',
    BUSINESS_KEY    VARCHAR(128) NULL COMMENT '业务 Key',
    MESSAGE_ID      VARCHAR(128) NULL COMMENT '消息 ID',
    STATUS          VARCHAR(32)  NOT NULL COMMENT '状态：PROCESSING、SUCCESS、FAILED',
    CONSUME_COUNT   INT          NOT NULL DEFAULT 0 COMMENT '消费次数',
    LAST_ERROR      VARCHAR(1000) NULL COMMENT '脱敏后的最近错误',
    CREATED_AT      DATETIME(3)  NOT NULL COMMENT '创建时间',
    UPDATED_AT      DATETIME(3)  NOT NULL COMMENT '更新时间',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MQ_CONSUME_IDEMPOTENT (IDEMPOTENT_KEY, CONSUMER_GROUP),
    KEY IDX_MQ_CONSUME_MESSAGE (MESSAGE_ID),
    KEY IDX_MQ_CONSUME_STATUS_UPDATE (STATUS, UPDATED_AT)
) COMMENT='RocketMQ JDBC 消费幂等记录表';
