CREATE TABLE PEACH_AUTH_FUNCTION
(
    ID           VARCHAR(32)  NOT NULL PRIMARY KEY COMMENT '逻辑ID',
    PARTY_CODE        VARCHAR(32)  NOT NULL COMMENT '参与者代码',
    PARTY_TYPE        VARCHAR(20)  NOT NULL COMMENT '参与者类型，角色编码',
    FUNC_CODE         VARCHAR(128) NOT NULL COMMENT '功能代码',
    FISCAL            SMALLINT(4)  NOT NULL COMMENT '年度',
    STATE             VARCHAR(20)  NULL COMMENT '功能状态',
    CREATE_USER       VARCHAR(32)  NULL COMMENT '创建用户',
    CREATE_TIME       VARCHAR(20)  NULL COMMENT '创建时间',
    APP_ID            VARCHAR(128) NULL COMMENT '应用ID',
    LAST_MODIFY_TIME  MEDIUMTEXT   NULL COMMENT '最新修改时间',
    IS_DELETE         TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (PARTY_CODE, PARTY_TYPE, FISCAL, FUNC_CODE)
) COMMENT='授权功能表';

CREATE INDEX AUTH_FUNCTION_PF_IDX
    ON PEACH_AUTH_FUNCTION (PARTY_CODE, FUNC_CODE, FISCAL);
