CREATE TABLE PEACH_NOTICE_READ_RECORD
(
    ID            VARCHAR(64) NOT NULL COMMENT '主键ID',
    NOTICE_CODE   VARCHAR(64) NOT NULL COMMENT '通知编码',
    READ_USER_ID  VARCHAR(64) NOT NULL COMMENT '阅读用户ID',
    READ_TIME     VARCHAR(20)     NULL COMMENT '阅读时间',
    TENANT_ID    VARCHAR(32) NOT NULL COMMENT '租户ID',
    ORG_ID       VARCHAR(32) NOT NULL COMMENT '机构ID',
    CREATED_TIME  VARCHAR(20)     NULL COMMENT '创建时间',
    CREATOR_ID    VARCHAR(32)     NULL COMMENT '创建人ID',
    MODIFY_TIME   VARCHAR(20)     NULL COMMENT '修改时间',
    MODIFIER_ID   VARCHAR(32)     NULL COMMENT '修改人ID',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_NOTICE_READ_CONTEXT (TENANT_ID, ORG_ID, NOTICE_CODE, READ_USER_ID),
    INDEX IDX_NOTICE_READ_CONTEXT_USER (TENANT_ID, ORG_ID, READ_USER_ID)
) COMMENT='通知阅读记录表';
