CREATE TABLE PEACH_IP_WHITELIST
(
    ID           VARCHAR(64)  NOT NULL COMMENT '主键ID',
    IP_ADDRESS   VARCHAR(64)  NOT NULL COMMENT 'IP地址',
    IP_DESC      VARCHAR(255)     NULL COMMENT 'IP说明',
    STATUS       INT         DEFAULT 1 COMMENT '状态，1启用，0禁用',
    TENANT_ID    VARCHAR(32)  NOT NULL COMMENT '租户ID',
    ORG_ID       VARCHAR(32)  NOT NULL COMMENT '机构ID',
    CREATED_TIME VARCHAR(20)      NULL COMMENT '创建时间',
    CREATOR_ID   VARCHAR(32)      NULL COMMENT '创建人ID',
    MODIFY_TIME  VARCHAR(20)      NULL COMMENT '修改时间',
    MODIFIER_ID  VARCHAR(32)      NULL COMMENT '修改人ID',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_IP_WHITELIST_CONTEXT_IP (TENANT_ID, ORG_ID, IP_ADDRESS),
    INDEX IDX_IP_WHITELIST_STATUS (STATUS, IP_ADDRESS)
) COMMENT='IP白名单表';
