CREATE TABLE PEACH_SCHEDULER_STATE_LOG
(
    ID             BIGINT       NOT NULL AUTO_INCREMENT COMMENT '状态日志主键',
    AGGREGATE_TYPE VARCHAR(32)  NOT NULL COMMENT '聚合类型：JOB、EXECUTION',
    AGGREGATE_ID   VARCHAR(128) NOT NULL COMMENT '聚合标识',
    FROM_STATE     VARCHAR(32)  NULL COMMENT '迁移前状态',
    EVENT          VARCHAR(32)  NOT NULL COMMENT '状态事件',
    TO_STATE       VARCHAR(32)  NOT NULL COMMENT '迁移后状态',
    OPERATOR_ID    VARCHAR(64)  NULL COMMENT '操作人 ID',
    REMARK         VARCHAR(512) NULL COMMENT '备注',
    CREATED_TIME   DATETIME(3)  NOT NULL COMMENT '创建时间',
    PRIMARY KEY (ID),
    KEY IDX_SCHEDULER_STATE_LOG_AGGREGATE (AGGREGATE_TYPE, AGGREGATE_ID, CREATED_TIME),
    KEY IDX_SCHEDULER_STATE_LOG_TIME (CREATED_TIME)
) COMMENT='调度状态迁移审计表';
