CREATE TABLE PEACH_AUTH_LOG
(
    LOG_ID            VARCHAR(38) NOT NULL COMMENT '日志ID',
    TENANT_ID         VARCHAR(32) NOT NULL COMMENT '租户ID',
    ORG_ID            VARCHAR(32) NOT NULL COMMENT '机构ID',
    OPERATOR_USER_ID  VARCHAR(32) NOT NULL COMMENT '操作人用户ID',
    OPERATOR_CODE     VARCHAR(42) NOT NULL COMMENT '操作人账号',
    OPERATOR_NAME     VARCHAR(42) NOT NULL COMMENT '操作人名称',
    USER_ID           VARCHAR(32) NOT NULL COMMENT '被授权用户ID',
    USER_CODE         VARCHAR(42) NOT NULL COMMENT '被授权用户账号',
    USER_NAME         VARCHAR(42) NOT NULL COMMENT '被授权用户名称',
    AUTH_DESCRIBE     MEDIUMTEXT  NOT NULL COMMENT '授权描述',
    OPERAT_TIME       VARCHAR(30) NOT NULL COMMENT '操作时间',
    PRIMARY KEY (LOG_ID)
) COMMENT='授权日志表';

CREATE INDEX IDX_AUTH_LOG_TENANT_ORG_TIME
    ON PEACH_AUTH_LOG (TENANT_ID, ORG_ID, OPERAT_TIME);
