CREATE TABLE PEACH_AUTH_PARTY
(
    ID               VARCHAR(32) NOT NULL COMMENT '主键ID',
    ROLE_CODE        VARCHAR(32) NOT NULL COMMENT '角色代码',
    ROLE_TYPE        VARCHAR(20) NOT NULL COMMENT '角色类型',
    FISCAL           SMALLINT(4) NOT NULL COMMENT '年度',
    PARTY_CODE       VARCHAR(32) NOT NULL COMMENT '参与者代码',
    PARTY_TYPE       VARCHAR(20) NOT NULL COMMENT '参与者类型',
    CREATE_USER      VARCHAR(32) NULL COMMENT '创建用户',
    CREATE_TIME      VARCHAR(20) NULL COMMENT '创建时间',
    LAST_MODIFY_TIME MEDIUMTEXT  NULL COMMENT '最新修改时间',
    IS_DELETE        TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (ROLE_CODE, ROLE_TYPE, FISCAL, PARTY_CODE, PARTY_TYPE)
) COMMENT='授权参与者表';

CREATE INDEX AUTH_PARTY_BUSI_IDX
    ON PEACH_AUTH_PARTY (ROLE_CODE, FISCAL);
