CREATE TABLE PEACH_SCHEDULER_HANDLER
(
    ID                  BIGINT       NOT NULL AUTO_INCREMENT COMMENT 'Handler 主键',
    APPLICATION_NAME    VARCHAR(128) NOT NULL COMMENT '业务应用名称',
    HANDLER_NAME        VARCHAR(128) NOT NULL COMMENT 'Handler 名称',
    DESCRIPTION         VARCHAR(512) NULL COMMENT 'Handler 说明',
    STATUS              VARCHAR(32)  NOT NULL COMMENT '状态：ONLINE、OFFLINE',
    INSTANCE_ID         VARCHAR(128) NULL COMMENT '最近上报实例标识',
    LAST_HEARTBEAT_TIME DATETIME(3)  NOT NULL COMMENT '最近心跳时间',
    CREATED_TIME        DATETIME(3)  NOT NULL COMMENT '创建时间',
    MODIFY_TIME         DATETIME(3)  NOT NULL COMMENT '修改时间',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SCHEDULER_HANDLER (APPLICATION_NAME, HANDLER_NAME),
    KEY IDX_SCHEDULER_HANDLER_STATUS (STATUS, LAST_HEARTBEAT_TIME)
) COMMENT='调度 Handler 注册白名单表';
