CREATE TABLE PEACH_DICT_ITEM
(
    ID           VARCHAR(64)  NOT NULL COMMENT '主键ID',
    DICT_CODE    VARCHAR(64)  NOT NULL COMMENT '字典编码',
    ITEM_CODE    VARCHAR(64)      NULL COMMENT '项编码',
    ITEM_VALUE   VARCHAR(255)     NULL COMMENT '项值',
    SORT_ORDER   INT              NULL COMMENT '排序号',
    MESSAGE_KEY  VARCHAR(128)     NULL COMMENT '国际化Key',
    EXTRA_JSON   TEXT             NULL COMMENT '扩展JSON',
    STATUS       INT              NULL COMMENT '状态',
    TENANT_ID    VARCHAR(32)  NOT NULL COMMENT '租户ID',
    ORG_ID       VARCHAR(32)  NOT NULL COMMENT '机构ID',
    CREATED_TIME VARCHAR(20)      NULL COMMENT '创建时间',
    CREATOR_ID   VARCHAR(32)      NULL COMMENT '创建人ID',
    MODIFY_TIME  VARCHAR(20)      NULL COMMENT '修改时间',
    MODIFIER_ID  VARCHAR(32)      NULL COMMENT '修改人ID',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_DICT_ITEM_CONTEXT_CODE (TENANT_ID, ORG_ID, DICT_CODE, ITEM_CODE),
    INDEX IDX_DICT_ITEM_CONTEXT_DICT (TENANT_ID, ORG_ID, DICT_CODE)
) COMMENT='字典项表';
