CREATE TABLE PEACH_CODE_RULE
(
    TENANT_ID       VARCHAR(32) NOT NULL COMMENT '租户ID',
    ORG_ID          VARCHAR(32) NOT NULL COMMENT '机构ID',
    CODE_PREFIX     VARCHAR(32) NOT NULL COMMENT '编码前缀，例如 MENU、NOTICE',
    MAX_CODE_WIDTH  INT         NOT NULL DEFAULT 8 COMMENT '数字部分最大长度，不足左侧补零',
    CURRENT_VALUE   BIGINT      NOT NULL DEFAULT 0 COMMENT '当前已提交的最大序号',
    STATUS          VARCHAR(16) NOT NULL DEFAULT 'ENABLE' COMMENT '规则状态',
    CREATED_TIME    VARCHAR(20) NULL COMMENT '创建时间',
    CREATOR_ID      VARCHAR(32) NULL COMMENT '创建人ID',
    MODIFY_TIME     VARCHAR(20) NULL COMMENT '修改时间',
    MODIFIER_ID     VARCHAR(32) NULL COMMENT '修改人ID',
    PRIMARY KEY (TENANT_ID, ORG_ID, CODE_PREFIX)
) COMMENT='租户业务编码规则与序列表';

-- 示例：每个租户分别维护自己的 MENU、NOTICE 序列。
-- INSERT INTO PEACH_CODE_RULE (TENANT_ID, CODE_PREFIX, MAX_CODE_WIDTH, CURRENT_VALUE, STATUS)
-- VALUES ('T001', 'MENU', 8, 0, 'ENABLE');
-- INSERT INTO PEACH_CODE_RULE (TENANT_ID, CODE_PREFIX, MAX_CODE_WIDTH, CURRENT_VALUE, STATUS)
-- VALUES ('T001', 'NOTICE', 8, 0, 'ENABLE');
