CREATE TABLE PEACH_SCHEDULER_EXECUTION_ATTEMPT
(
    EXECUTION_ID      VARCHAR(64)  NOT NULL COMMENT '执行实例 ID',
    ATTEMPT_NO        INT          NOT NULL COMMENT '尝试序号',
    EXECUTOR_INSTANCE VARCHAR(128) NULL COMMENT '执行器实例标识',
    STATE             VARCHAR(32)  NOT NULL COMMENT '尝试状态',
    START_TIME        DATETIME(3)  NOT NULL COMMENT '尝试开始时间',
    FINISH_TIME       DATETIME(3)  NULL COMMENT '尝试结束时间',
    DURATION_MS       BIGINT       NULL COMMENT '尝试耗时毫秒数',
    ERROR_TYPE        VARCHAR(128) NULL COMMENT '失败类型',
    ERROR_MESSAGE     VARCHAR(1000) NULL COMMENT '脱敏后的失败摘要',
    CREATED_TIME      DATETIME(3)  NOT NULL COMMENT '创建时间',
    PRIMARY KEY (EXECUTION_ID, ATTEMPT_NO),
    KEY IDX_SCHEDULER_ATTEMPT_TIME (CREATED_TIME),
    KEY IDX_SCHEDULER_ATTEMPT_STATE (STATE, CREATED_TIME)
) COMMENT='调度执行尝试历史表';
