CREATE TABLE PEACH_SCHEDULER_OPERATION_LOG
(
    ID           BIGINT       NOT NULL AUTO_INCREMENT COMMENT '操作日志主键',
    OPERATION    VARCHAR(64)  NOT NULL COMMENT '操作编码，如 RUN、RETRY、CANCEL',
    TARGET_TYPE  VARCHAR(32)  NOT NULL COMMENT '目标类型：JOB、EXECUTION',
    TARGET_ID    VARCHAR(128) NOT NULL COMMENT '目标标识',
    OPERATOR_ID  VARCHAR(64)  NULL COMMENT '操作人 ID',
    REASON       VARCHAR(512) NULL COMMENT '操作原因',
    RESULT       VARCHAR(32)  NOT NULL COMMENT '操作结果：SUCCESS、FAILED',
    CREATED_TIME DATETIME(3)  NOT NULL COMMENT '创建时间',
    PRIMARY KEY (ID),
    KEY IDX_SCHEDULER_OPERATION_TARGET (TARGET_TYPE, TARGET_ID, CREATED_TIME),
    KEY IDX_SCHEDULER_OPERATION_OPERATOR (OPERATOR_ID, CREATED_TIME),
    KEY IDX_SCHEDULER_OPERATION_TIME (CREATED_TIME)
) COMMENT='调度人工操作审计表';
