CREATE TABLE PEACH_ROUTER
(
    ROUTER_ID     VARCHAR(64)  NOT NULL COMMENT '主键',
    ROUTER_CODE   VARCHAR(100) NOT NULL COMMENT '路由代码',
    ROUTER_NAME   VARCHAR(100) NOT NULL COMMENT '路由名称',
    ROUTER_URL    VARCHAR(100) NOT NULL COMMENT '路由路径',
    FILE_PATH     VARCHAR(255) NOT NULL COMMENT '文件路径',
    IS_AUTH       TINYINT(1) DEFAULT 1 NOT NULL COMMENT '是否需要授权',
    IS_CACHE      TINYINT(1) DEFAULT 1 NOT NULL COMMENT '是否缓存',
    MODULE_CODE   VARCHAR(10)  NOT NULL COMMENT '模块代码',
    ROUTER_LEVEL  INT(4) NOT NULL COMMENT '路由级次',
    PRIMARY KEY (ROUTER_ID),
    UNIQUE KEY UNI_CODE_KEY (ROUTER_CODE),
    UNIQUE KEY UNI_URL_KEY (ROUTER_URL)
) COMMENT='路由管理表';
