CREATE TABLE PEACH_RESOURCE
(
    RESOURCE_ID      VARCHAR(32)  NOT  NULL COMMENT '资源ID',
    FUNC_CODE        VARCHAR(128)      NULL COMMENT '功能编码',
    RESOURCE_TYPE    VARCHAR(20)       NULL COMMENT '资源类型',
    RESOURCE_CODE    VARCHAR(64)       NULL COMMENT '资源编码',
    RESOURCE_NAME    VARCHAR(32)       NULL COMMENT '资源名称',
    TENANT_ID        VARCHAR(32)  NOT NULL COMMENT '租户ID',
    APP_ID           VARCHAR(32)  NOT NULL COMMENT '应用ID',
    CREATED_TIME     VARCHAR(20)       NULL COMMENT '创建时间',
    CREATOR_ID       VARCHAR(32)       NULL COMMENT '创建人ID',
    MODIFY_TIME      VARCHAR(20)       NULL COMMENT '修改时间',
    MODIFIER_ID      VARCHAR(32)       NULL COMMENT '修改人ID',
    IS_DELETE        TINYINT(1)   DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (RESOURCE_ID),
    UNIQUE KEY UK_RESOURCE_TENANT_APP_FUNC_CODE (TENANT_ID, APP_ID, FUNC_CODE, RESOURCE_CODE)
) COMMENT='资源表';

CREATE INDEX RESOURCE_BUSI_IDX
    ON PEACH_RESOURCE (TENANT_ID, APP_ID, FUNC_CODE, RESOURCE_CODE);
