CREATE TABLE PEACH_VALUE_SET_ITEM
(
    ID            VARCHAR(64)  NOT NULL COMMENT '主键ID',
    VALUE_SET_CODE VARCHAR(64) NOT NULL COMMENT '值集编码',
    ITEM_CODE     VARCHAR(64)  NOT NULL COMMENT '项编码',
    ITEM_VALUE    VARCHAR(255) NULL COMMENT '项值',
    MESSAGE_KEY   VARCHAR(128) NULL COMMENT '国际化Key',
    SOURCE_TYPE   VARCHAR(32)  NULL COMMENT '来源类型',
    SORT_ORDER    INT          NULL COMMENT '排序号',
    STATUS        INT          NULL COMMENT '状态',
    VISIBLE_FLAG  INT          NULL COMMENT '是否可见',
    EXTRA_JSON    TEXT         NULL COMMENT '扩展JSON',
    CREATED_TIME  VARCHAR(20)  NULL COMMENT '创建时间',
    CREATOR_ID    VARCHAR(32)  NULL COMMENT '创建人ID',
    MODIFY_TIME   VARCHAR(20)  NULL COMMENT '修改时间',
    MODIFIER_ID   VARCHAR(32)  NULL COMMENT '修改人ID',
    PRIMARY KEY (ID)
) COMMENT='值集项表';
