CREATE TABLE PEACH_VALUE_SET
(
    ID            VARCHAR(64)  NOT NULL COMMENT '主键ID',
    VALUE_SET_CODE VARCHAR(64) NOT NULL COMMENT '值集编码',
    VALUE_SET_NAME VARCHAR(128) NULL COMMENT '值集名称',
    MODULE_CODE   VARCHAR(64)  NULL COMMENT '模块编码',
    SOURCE_TYPE   VARCHAR(32)  NULL COMMENT '来源类型',
    DESCRIPTION   VARCHAR(500) NULL COMMENT '描述',
    STATUS        INT          NULL COMMENT '状态',
    TENANT_ID     VARCHAR(32)  NOT NULL COMMENT '租户ID',
    ORG_ID        VARCHAR(32)  NOT NULL COMMENT '机构ID',
    CREATED_TIME  VARCHAR(20)  NULL COMMENT '创建时间',
    CREATOR_ID    VARCHAR(32)  NULL COMMENT '创建人ID',
    MODIFY_TIME   VARCHAR(20)  NULL COMMENT '修改时间',
    MODIFIER_ID   VARCHAR(32)  NULL COMMENT '修改人ID',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_VALUE_SET_CONTEXT_CODE (TENANT_ID, ORG_ID, VALUE_SET_CODE),
    INDEX IDX_VALUE_SET_CONTEXT (TENANT_ID, ORG_ID)
) COMMENT='值集配置表';
