CREATE TABLE PEACH_TENANT
(
    TENANT_ID    VARCHAR(32)  NOT NULL COMMENT '租户ID',
    TENANT_CODE  VARCHAR(64)  NOT NULL COMMENT '租户编码',
    TENANT_NAME  VARCHAR(128) NOT NULL COMMENT '租户名称',
    STATUS       VARCHAR(16)  DEFAULT 'ENABLE' COMMENT '状态',
    SORT_NUM     INT          DEFAULT 0 COMMENT '排序',
    IS_DELETE    INT          DEFAULT 0 COMMENT '逻辑删除',
    CREATED_TIME VARCHAR(20)  NULL COMMENT '创建时间',
    CREATOR_ID   VARCHAR(32)  NULL COMMENT '创建人ID',
    MODIFY_TIME  VARCHAR(20)  NULL COMMENT '修改时间',
    MODIFIER_ID  VARCHAR(32)  NULL COMMENT '修改人ID',
    PRIMARY KEY (TENANT_ID),
    UNIQUE KEY UK_TENANT_CODE (TENANT_CODE)
) COMMENT='租户表';
