CREATE TABLE PEACH_AUTH_RESOURCE
(
    RESOURCE_ID       VARCHAR(32)  NOT NULL COMMENT '逻辑ID',
    PARTY_CODE        VARCHAR(32)  NOT NULL COMMENT '参与者代码,角色编码',
    FUNC_CODE         VARCHAR(64)  NOT NULL COMMENT '功能代码',
    OP_TYPE           VARCHAR(20)  NULL COMMENT '操作类型',
    RESOURCE_CODE     VARCHAR(64)  NULL COMMENT '资源编码',
    RESOURCE_NAME     VARCHAR(32)  NULL COMMENT '资源名称',
    APP_ID            VARCHAR(32)  NULL COMMENT '应用ID',
    LAST_MODIFY_TIME  MEDIUMTEXT   NULL COMMENT '最新修改时间',
    IS_DELETE         TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    FISCAL            SMALLINT(4)  NOT NULL COMMENT '年度',
    PRIMARY KEY (RESOURCE_ID)
) COMMENT='授权资源表';

CREATE INDEX AUTH_RESOURCE_BUSI_FISCAL_IDX
    ON PEACH_AUTH_RESOURCE (PARTY_CODE, FUNC_CODE, FISCAL);

CREATE INDEX AUTH_RESOURCE_BUSI_IDX
    ON PEACH_AUTH_RESOURCE (FUNC_CODE, RESOURCE_CODE);
