CREATE TABLE PEACH_ROUTER
(
    ROUTER_ID     VARCHAR(64)  NOT NULL COMMENT '主键',
    ROUTER_CODE   VARCHAR(100) NOT NULL COMMENT '路由代码',
    ROUTER_NAME   VARCHAR(100) NOT NULL COMMENT '路由名称',
    ROUTER_URL    VARCHAR(100) NOT NULL COMMENT '路由路径',
    FILE_PATH     VARCHAR(255) NOT NULL COMMENT '文件路径',
    IS_AUTH       TINYINT(1) DEFAULT 1 NOT NULL COMMENT '是否需要授权',
    IS_CACHE      TINYINT(1) DEFAULT 1 NOT NULL COMMENT '是否缓存',
    MODULE_CODE   VARCHAR(10)  NOT NULL COMMENT '模块代码',
    ROUTER_LEVEL  INT(4) NOT NULL COMMENT '路由级次',
    TENANT_ID     VARCHAR(32)  NOT NULL COMMENT '租户ID',
    APP_ID        VARCHAR(32)  NOT NULL COMMENT '应用ID',
    CREATED_TIME  VARCHAR(20)  NULL COMMENT '创建时间',
    CREATOR_ID    VARCHAR(32)  NULL COMMENT '创建人ID',
    MODIFY_TIME   VARCHAR(20)  NULL COMMENT '修改时间',
    MODIFIER_ID   VARCHAR(32)  NULL COMMENT '修改人ID',
    PRIMARY KEY (ROUTER_ID),
    UNIQUE KEY UK_ROUTER_TENANT_APP_CODE (TENANT_ID, APP_ID, ROUTER_CODE),
    UNIQUE KEY UK_ROUTER_TENANT_APP_URL (TENANT_ID, APP_ID, ROUTER_URL),
    INDEX IDX_ROUTER_TENANT_APP (TENANT_ID, APP_ID)
) COMMENT='路由管理表';
