CREATE TABLE PEACH_AUTH_FUNCTION
(
    ID               VARCHAR(32)  NOT NULL COMMENT '逻辑ID',
    TENANT_ID        VARCHAR(32)  NOT NULL COMMENT '租户ID',
    ORG_ID           VARCHAR(32)  NOT NULL COMMENT '机构ID',
    PARTY_CODE       VARCHAR(32)  NOT NULL COMMENT '参与者代码',
    PARTY_TYPE       VARCHAR(20)  NOT NULL COMMENT '参与者类型，角色编码',
    FUNC_CODE        VARCHAR(128) NOT NULL COMMENT '功能代码',
    FISCAL           SMALLINT(4)  NOT NULL COMMENT '年度',
    STATE            VARCHAR(20)  NULL COMMENT '功能状态',
    CREATED_TIME     VARCHAR(20)  NULL COMMENT '创建时间',
    CREATOR_ID       VARCHAR(32)  NULL COMMENT '创建人ID',
    MODIFY_TIME      VARCHAR(20)  NULL COMMENT '修改时间',
    MODIFIER_ID      VARCHAR(32)  NULL COMMENT '修改人ID',
    APP_ID           VARCHAR(32)  NOT NULL COMMENT '应用ID',
    IS_DELETE        TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_AUTH_FUNCTION_CONTEXT (TENANT_ID, ORG_ID, APP_ID, PARTY_CODE, PARTY_TYPE, FISCAL, FUNC_CODE)
) COMMENT='授权功能表';

CREATE INDEX AUTH_FUNCTION_PF_IDX
    ON PEACH_AUTH_FUNCTION (TENANT_ID, ORG_ID, APP_ID, PARTY_CODE, FUNC_CODE, FISCAL);
