CREATE TABLE PEACH_SITE_MESSAGE
(
    ID                  VARCHAR(64)  NOT NULL COMMENT '消息ID',
    MESSAGE_CODE        VARCHAR(64)  NOT NULL COMMENT '消息编码',
    RECEIVER_ID         VARCHAR(64)  NOT NULL COMMENT '接收用户ID',
    TITLE_MESSAGE_KEY   VARCHAR(128) NULL COMMENT '标题消息Key',
    CONTENT_MESSAGE_KEY VARCHAR(128) NULL COMMENT '内容消息Key',
    MESSAGE_TYPE        VARCHAR(32)  NULL COMMENT '消息类型',
    SOURCE_TYPE         VARCHAR(32)  NULL COMMENT '来源类型',
    SOURCE_CODE         VARCHAR(64)  NULL COMMENT '来源编码',
    READ_FLAG           INT          NULL COMMENT '是否已读',
    SEND_STATUS         VARCHAR(32)  NULL COMMENT '发送状态',
    CREATED_TIME        VARCHAR(20)  NULL COMMENT '创建时间',
    CREATOR_ID          VARCHAR(32)  NULL COMMENT '创建人ID',
    MODIFY_TIME         VARCHAR(20)  NULL COMMENT '修改时间',
    MODIFIER_ID         VARCHAR(32)  NULL COMMENT '修改人ID',
    PRIMARY KEY (ID)
) COMMENT='站内消息表';
