CREATE TABLE PEACH_LANGUAGE
(
    ID            VARCHAR(64)  NOT NULL COMMENT '语言ID',
    LANGUAGE_CODE VARCHAR(32)  NOT NULL COMMENT '语言编码',
    LANGUAGE_NAME VARCHAR(128)     NULL COMMENT '语言名称',
    NATIVE_NAME   VARCHAR(128)     NULL COMMENT '本地化名称',
    ICON          VARCHAR(255)     NULL COMMENT '语言图标',
    STATUS        INT              NULL COMMENT '状态',
    DEFAULT_FLAG   INT             NULL COMMENT '是否默认',
    SORT_ORDER    INT              NULL COMMENT '排序',
    CREATED_TIME  VARCHAR(20)      NULL COMMENT '创建时间',
    CREATOR_ID    VARCHAR(32)      NULL COMMENT '创建人ID',
    MODIFY_TIME   VARCHAR(20)      NULL COMMENT '修改时间',
    MODIFIER_ID   VARCHAR(32)      NULL COMMENT '修改人ID',
    PRIMARY KEY (ID)
) COMMENT='语言设置表';
