CREATE TABLE PEACH_AUTH_RESOURCE
(
    RESOURCE_ID      VARCHAR(32)  NOT NULL COMMENT '逻辑ID',
    TENANT_ID        VARCHAR(32)  NOT NULL COMMENT '租户ID',
    ORG_ID           VARCHAR(32)  NOT NULL COMMENT '机构ID',
    PARTY_CODE       VARCHAR(32)  NOT NULL COMMENT '参与者代码/角色编码',
    FUNC_CODE        VARCHAR(64)  NOT NULL COMMENT '功能代码',
    OP_TYPE          VARCHAR(20)  NULL COMMENT '操作类型',
    RESOURCE_CODE    VARCHAR(64)  NULL COMMENT '资源编码',
    RESOURCE_NAME    VARCHAR(32)  NULL COMMENT '资源名称',
    APP_ID           VARCHAR(32)  NULL COMMENT '应用ID',
    CREATED_TIME     VARCHAR(20)  NULL COMMENT '创建时间',
    CREATOR_ID       VARCHAR(32)  NULL COMMENT '创建人ID',
    MODIFY_TIME      VARCHAR(20)  NULL COMMENT '修改时间',
    MODIFIER_ID      VARCHAR(32)  NULL COMMENT '修改人ID',
    IS_DELETE        TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    FISCAL           SMALLINT(4)  NOT NULL COMMENT '年度',
    PRIMARY KEY (RESOURCE_ID)
) COMMENT='授权资源表';

CREATE INDEX AUTH_RESOURCE_BUSI_FISCAL_IDX
    ON PEACH_AUTH_RESOURCE (TENANT_ID, ORG_ID, PARTY_CODE, FUNC_CODE, FISCAL);

CREATE INDEX AUTH_RESOURCE_BUSI_IDX
    ON PEACH_AUTH_RESOURCE (FUNC_CODE, RESOURCE_CODE);
