CREATE TABLE PEACH_USER_ORG
(
    ID           VARCHAR(32) NOT NULL COMMENT '主键ID',
    USER_ID      VARCHAR(32) NOT NULL COMMENT '用户ID',
    TENANT_ID    VARCHAR(32) NOT NULL COMMENT '租户ID',
    ORG_ID       VARCHAR(32) NOT NULL COMMENT '机构ID',
    IS_DEFAULT   TINYINT(1) DEFAULT 0 COMMENT '是否默认机构',
    STATUS       VARCHAR(20) NULL COMMENT '状态',
    CREATED_TIME VARCHAR(20) NULL COMMENT '创建时间',
    CREATOR_ID   VARCHAR(32) NULL COMMENT '创建人ID',
    MODIFY_TIME  VARCHAR(20) NULL COMMENT '修改时间',
    MODIFIER_ID  VARCHAR(32) NULL COMMENT '修改人ID',
    IS_DELETE    TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_USER_ORG (TENANT_ID, USER_ID, ORG_ID),
    INDEX IDX_USER_ORG_USER (TENANT_ID, USER_ID),
    INDEX IDX_USER_ORG_ORG (TENANT_ID, ORG_ID)
) COMMENT='用户机构关系表';
