CREATE TABLE PEACH_FUNCTION
(
    FUNC_CODE        VARCHAR(128) NOT NULL COMMENT '功能编码',
    PARENT_FUNC_CODE VARCHAR(32)      NULL COMMENT '父功能编码',
    FUNC_NAME        VARCHAR(32)      NULL COMMENT '功能名称',
    FUNC_DESC        VARCHAR(32)      NULL COMMENT '功能描述',
    FUNC_URL         VARCHAR(128)     NULL COMMENT '功能URL',
    FUNC_SEQ         VARCHAR(128)     NULL COMMENT '功能序列号',
    FUNC_TYPE        VARCHAR(20)      NULL COMMENT '功能类型',
    IS_MENU          TINYINT(1) DEFAULT 0  COMMENT '是否菜单',
    IS_AUTHORIZE     TINYINT(1) DEFAULT 0  COMMENT '是否访问授权',
    APP_ID           VARCHAR(32)      NULL COMMENT '应用ID',
    CREATED_TIME     VARCHAR(20)      NULL COMMENT '创建时间',
    CREATOR_ID       VARCHAR(32)      NULL COMMENT '创建人ID',
    MODIFY_TIME      VARCHAR(20)      NULL COMMENT '修改时间',
    MODIFIER_ID      VARCHAR(32)      NULL COMMENT '修改人ID',
    IS_DISABLE       TINYINT(1) DEFAULT 0  COMMENT '是否禁用',
    IS_DELETE        TINYINT(1) DEFAULT 0  COMMENT '是否删除',
    PRIMARY KEY (FUNC_CODE)
) COMMENT='应用功能表';
