CREATE TABLE PEACH_ROLE
(
    ROLE_ID          VARCHAR(32)  NOT NULL COMMENT '角色ID',
    TENANT_ID        VARCHAR(32)  NOT NULL COMMENT '租户ID',
    ORG_ID           VARCHAR(32)  NOT NULL COMMENT '机构ID',
    ROLE_CODE        VARCHAR(20)  NOT NULL COMMENT '角色编码',
    FISCAL           SMALLINT(4)  NOT NULL COMMENT '年度',
    ROLE_NAME        VARCHAR(64)  NULL COMMENT '角色名称',
    ROLE_DESC        VARCHAR(64)  NULL COMMENT '角色描述',
    ROLE_SCOPE       VARCHAR(20)  NULL COMMENT '角色范围',
    ROLE_TYPE        VARCHAR(20)  NULL COMMENT '角色类型',
    CREATED_TIME     VARCHAR(20)  NULL COMMENT '创建时间',
    CREATOR_ID       VARCHAR(32)  NULL COMMENT '创建人ID',
    MODIFY_TIME      VARCHAR(20)  NULL COMMENT '修改时间',
    MODIFIER_ID      VARCHAR(32)  NULL COMMENT '修改人ID',
    IS_DELETE        TINYINT(1)   DEFAULT 0 NULL COMMENT '是否删除',
    SKIP_URL         VARCHAR(64)  NULL COMMENT '角色登陆跳转',
    PRIMARY KEY (ROLE_ID)
) COMMENT='角色表';

CREATE UNIQUE INDEX UK_ROLE_CODE
    ON PEACH_ROLE (TENANT_ID, ORG_ID, ROLE_CODE, FISCAL);

CREATE INDEX IDX_ROLE_TENANT_ORG
    ON PEACH_ROLE (TENANT_ID, ORG_ID);
