CREATE TABLE PEACH_APPLICATION
(
    APP_ID           VARCHAR(32) NOT NULL COMMENT '应用ID',
    APP_NAME         VARCHAR(64) NULL COMMENT '应用名称',
    APP_TYPE         VARCHAR(20) NULL COMMENT '应用类型',
    IS_OPEN          TINYINT(1)  DEFAULT 0 COMMENT '是否启用',
    APP_DESC         VARCHAR(32) NULL COMMENT '应用描述',
    LOGOUT_URL       VARCHAR(128) NULL COMMENT '退出URL',
    SORT_NUM         VARCHAR(32) NULL COMMENT '显示顺序',
    LAST_MODIFY_TIME MEDIUMTEXT  NULL COMMENT '最新修改时间',
    IS_DELETE        TINYINT(1)  DEFAULT 0 NULL COMMENT '是否删除',
    PRIMARY KEY (APP_ID)
);
