CREATE TABLE PEACH_DICT_TYPE
(
    ID           VARCHAR(64)  NOT NULL COMMENT '主键ID',
    DICT_CODE    VARCHAR(64)  NOT NULL COMMENT '字典编码',
    DICT_NAME    VARCHAR(128)     NULL COMMENT '字典名称',
    MODULE_CODE  VARCHAR(64)      NULL COMMENT '模块编码',
    SORT_ORDER   INT              NULL COMMENT '排序号',
    STATUS       INT              NULL COMMENT '状态',
    CREATED_TIME VARCHAR(20)      NULL COMMENT '创建时间',
    CREATOR_ID   VARCHAR(32)      NULL COMMENT '创建人ID',
    MODIFY_TIME  VARCHAR(20)      NULL COMMENT '修改时间',
    MODIFIER_ID  VARCHAR(32)      NULL COMMENT '修改人ID',
    PRIMARY KEY (ID)
) COMMENT='字典类型表';
