CREATE TABLE PEACH_AUTH_PARTY
(
    ID               VARCHAR(32)  NOT NULL COMMENT '主键ID',
    TENANT_ID        VARCHAR(32)  NOT NULL COMMENT '租户ID',
    ORG_ID           VARCHAR(32)  NOT NULL COMMENT '机构ID',
    ROLE_CODE        VARCHAR(32)  NOT NULL COMMENT '角色代码',
    ROLE_TYPE        VARCHAR(20)  NOT NULL COMMENT '角色类型',
    FISCAL           SMALLINT(4)  NOT NULL COMMENT '年度',
    PARTY_CODE       VARCHAR(32)  NOT NULL COMMENT '参与者代码',
    PARTY_TYPE       VARCHAR(20)  NOT NULL COMMENT '参与者类型',
    CREATED_TIME     VARCHAR(20)  NULL COMMENT '创建时间',
    CREATOR_ID       VARCHAR(32)  NULL COMMENT '创建人ID',
    MODIFY_TIME      VARCHAR(20)  NULL COMMENT '修改时间',
    MODIFIER_ID      VARCHAR(32)  NULL COMMENT '修改人ID',
    IS_DELETE        TINYINT(1) DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (TENANT_ID, ORG_ID, ROLE_CODE, ROLE_TYPE, FISCAL, PARTY_CODE, PARTY_TYPE)
) COMMENT='授权参与者表';

CREATE INDEX AUTH_PARTY_BUSI_IDX
    ON PEACH_AUTH_PARTY (TENANT_ID, ORG_ID, ROLE_CODE, FISCAL);
