CREATE TABLE PEACH_AUTH_LOG
(
    LOG_ID         VARCHAR(38) NOT NULL COMMENT '日志ID',
    OPERATOR_CODE  VARCHAR(42) NOT NULL COMMENT '操作人账号',
    OPERATOR_NAME  VARCHAR(42) NOT NULL COMMENT '操作人名称',
    USER_CODE      VARCHAR(42) NOT NULL COMMENT '被授权用户账号',
    USER_NAME      VARCHAR(42) NOT NULL COMMENT '被授权用户名称',
    AUTH_DESCRIBE  MEDIUMTEXT  NOT NULL COMMENT '授权描述',
    OPERAT_TIME    VARCHAR(30) NOT NULL COMMENT '操作时间',
    PRIMARY KEY (LOG_ID)
) COMMENT='授权日志表';
