CREATE TABLE PEACH_USER_AVATAR_HISTORY
(
    AVATAR_HISTORY_ID VARCHAR(32) NOT NULL COMMENT '头像历史ID',
    USER_ID           VARCHAR(32) NOT NULL COMMENT '用户ID',
    FILE_ID           VARCHAR(32) NOT NULL COMMENT '文件服务业务文件ID',
    SORT_NO           INT         NOT NULL COMMENT '排序号，1为最近使用',
    IS_CURRENT        TINYINT(1)  DEFAULT 0 COMMENT '是否当前头像',
    IS_DELETE         TINYINT(1)  DEFAULT 0 COMMENT '逻辑删除',
    CREATED_TIME      VARCHAR(20) NULL COMMENT '创建时间',
    CREATOR_ID        VARCHAR(32) NULL COMMENT '创建人ID',
    MODIFY_TIME       VARCHAR(20) NULL COMMENT '修改时间',
    MODIFIER_ID       VARCHAR(32) NULL COMMENT '修改人ID',
    PRIMARY KEY (AVATAR_HISTORY_ID),
    UNIQUE KEY UK_USER_AVATAR_FILE (USER_ID, FILE_ID),
    INDEX IDX_USER_AVATAR_ORDER (USER_ID, IS_DELETE, SORT_NO),
    INDEX IDX_USER_AVATAR_CURRENT (USER_ID, IS_CURRENT, IS_DELETE)
) COMMENT='用户头像历史表';
