CREATE TABLE PEACH_MULTI_MESSAGE
(
    ID             VARCHAR(64)  NOT NULL COMMENT '主键ID',
    MESSAGE_KEY    VARCHAR(128) NOT NULL COMMENT '消息Key',
    LOCALE         VARCHAR(32)  NOT NULL COMMENT '语言区域',
    MODULE_CODE    VARCHAR(64)      NULL COMMENT '模块编码',
    MESSAGE_TYPE   VARCHAR(32)      NULL COMMENT '消息类型',
    USAGE_SCOPE    VARCHAR(32)      NULL COMMENT '使用范围',
    MESSAGE_CONTENT TEXT            NULL COMMENT '消息内容',
    DESCRIPTION    VARCHAR(500)     NULL COMMENT '描述',
    STATUS         INT              NULL COMMENT '状态',
    TENANT_ID      VARCHAR(32)  NOT NULL COMMENT '租户ID',
    ORG_ID         VARCHAR(32)  NOT NULL COMMENT '机构ID',
    CREATED_TIME   VARCHAR(20)      NULL COMMENT '创建时间',
    CREATOR_ID     VARCHAR(32)      NULL COMMENT '创建人ID',
    MODIFY_TIME    VARCHAR(20)      NULL COMMENT '修改时间',
    MODIFIER_ID    VARCHAR(32)      NULL COMMENT '修改人ID',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MESSAGE_CONTEXT_KEY_LOCALE (TENANT_ID, ORG_ID, MESSAGE_KEY, LOCALE),
    INDEX IDX_MESSAGE_CONTEXT (TENANT_ID, ORG_ID)
) COMMENT='多语言消息表';
