CREATE TABLE PEACH_RESOURCE
(
    RESOURCE_ID       VARCHAR(32)  NOT NULL COMMENT '资源ID',
    FUNC_CODE         VARCHAR(128) NULL COMMENT '功能编码',
    RESOURCE_TYPE     VARCHAR(20)  NULL COMMENT '资源类型',
    RESOURCE_CODE     VARCHAR(64)  NULL COMMENT '资源编码',
    RESOURCE_NAME     VARCHAR(32)  NULL COMMENT '资源名称',
    APP_ID            VARCHAR(32)  NULL COMMENT '应用ID',
    LAST_MODIFY_TIME  MEDIUMTEXT   NULL COMMENT '最新修改时间',
    IS_DELETE         TINYINT(1)   DEFAULT 0 COMMENT '是否删除',
    PRIMARY KEY (RESOURCE_ID)
) COMMENT='资源表';

CREATE INDEX RESOURCE_BUSI_IDX
    ON PEACH_RESOURCE (FUNC_CODE, RESOURCE_CODE);
