-- Quartz JDBC JobStore 集群表（peach-scheduled Quartz Provider 运行时投影，非任务事实源）
-- 事实源见 PEACH_SCHEDULER_* 单表脚本；Scheduler 名称默认为 peachScheduler

CREATE TABLE QRTZ_JOB_DETAILS
(
    SCHED_NAME        VARCHAR(120) NOT NULL COMMENT 'Scheduler 名称',
    JOB_NAME          VARCHAR(200) NOT NULL COMMENT 'Job 名称',
    JOB_GROUP         VARCHAR(200) NOT NULL COMMENT 'Job 分组',
    DESCRIPTION       VARCHAR(250) NULL COMMENT 'Job 描述',
    JOB_CLASS_NAME    VARCHAR(250) NOT NULL COMMENT 'Job 实现类全名',
    IS_DURABLE        VARCHAR(1)   NOT NULL COMMENT '是否持久化',
    IS_NONCONCURRENT  VARCHAR(1)   NOT NULL COMMENT '是否禁止并发',
    IS_UPDATE_DATA    VARCHAR(1)   NOT NULL COMMENT '是否更新 JobData',
    REQUESTS_RECOVERY VARCHAR(1)   NOT NULL COMMENT '是否请求恢复',
    JOB_DATA          BLOB         NULL COMMENT 'Job 附加数据',
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz Job 详情表';

CREATE TABLE QRTZ_TRIGGERS
(
    SCHED_NAME     VARCHAR(120) NOT NULL COMMENT 'Scheduler 名称',
    TRIGGER_NAME   VARCHAR(200) NOT NULL COMMENT 'Trigger 名称',
    TRIGGER_GROUP  VARCHAR(200) NOT NULL COMMENT 'Trigger 分组',
    JOB_NAME       VARCHAR(200) NOT NULL COMMENT '关联 Job 名称',
    JOB_GROUP      VARCHAR(200) NOT NULL COMMENT '关联 Job 分组',
    DESCRIPTION    VARCHAR(250) NULL COMMENT 'Trigger 描述',
    NEXT_FIRE_TIME BIGINT(13)   NULL COMMENT '下次触发时间戳',
    PREV_FIRE_TIME BIGINT(13)   NULL COMMENT '上次触发时间戳',
    PRIORITY       INTEGER      NULL COMMENT '优先级',
    TRIGGER_STATE  VARCHAR(16)  NOT NULL COMMENT 'Trigger 状态',
    TRIGGER_TYPE   VARCHAR(8)   NOT NULL COMMENT 'Trigger 类型',
    START_TIME     BIGINT(13)   NOT NULL COMMENT '开始时间戳',
    END_TIME       BIGINT(13)   NULL COMMENT '结束时间戳',
    CALENDAR_NAME  VARCHAR(200) NULL COMMENT '日历名称',
    MISFIRE_INSTR  SMALLINT(2)  NULL COMMENT 'Misfire 指令',
    JOB_DATA       BLOB         NULL COMMENT 'Trigger 附加数据',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    KEY IDX_QRTZ_T_J (SCHED_NAME, JOB_NAME, JOB_GROUP),
    KEY IDX_QRTZ_T_JG (SCHED_NAME, JOB_GROUP),
    KEY IDX_QRTZ_T_C (SCHED_NAME, CALENDAR_NAME),
    KEY IDX_QRTZ_T_G (SCHED_NAME, TRIGGER_GROUP),
    KEY IDX_QRTZ_T_STATE (SCHED_NAME, TRIGGER_STATE),
    KEY IDX_QRTZ_T_N_STATE (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE),
    KEY IDX_QRTZ_T_N_G_STATE (SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE),
    KEY IDX_QRTZ_T_NEXT_FIRE_TIME (SCHED_NAME, NEXT_FIRE_TIME),
    KEY IDX_QRTZ_T_NFT_ST (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME),
    KEY IDX_QRTZ_T_NFT_MISFIRE (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME),
    KEY IDX_QRTZ_T_NFT_ST_MISFIRE (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE),
    KEY IDX_QRTZ_T_NFT_ST_MISFIRE_GRP (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz Trigger 表';

CREATE TABLE QRTZ_SIMPLE_TRIGGERS
(
    SCHED_NAME      VARCHAR(120) NOT NULL COMMENT 'Scheduler 名称',
    TRIGGER_NAME    VARCHAR(200) NOT NULL COMMENT 'Trigger 名称',
    TRIGGER_GROUP   VARCHAR(200) NOT NULL COMMENT 'Trigger 分组',
    REPEAT_COUNT    BIGINT(7)    NOT NULL COMMENT '重复次数',
    REPEAT_INTERVAL BIGINT(12)   NOT NULL COMMENT '重复间隔毫秒数',
    TIMES_TRIGGERED BIGINT(10)   NOT NULL COMMENT '已触发次数',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz Simple Trigger 表';

CREATE TABLE QRTZ_CRON_TRIGGERS
(
    SCHED_NAME      VARCHAR(120) NOT NULL COMMENT 'Scheduler 名称',
    TRIGGER_NAME    VARCHAR(200) NOT NULL COMMENT 'Trigger 名称',
    TRIGGER_GROUP   VARCHAR(200) NOT NULL COMMENT 'Trigger 分组',
    CRON_EXPRESSION VARCHAR(120) NOT NULL COMMENT 'Cron 表达式',
    TIME_ZONE_ID    VARCHAR(80)  NULL COMMENT '时区 ID',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz Cron Trigger 表';

CREATE TABLE QRTZ_SIMPROP_TRIGGERS
(
    SCHED_NAME    VARCHAR(120)   NOT NULL COMMENT 'Scheduler 名称',
    TRIGGER_NAME  VARCHAR(200)   NOT NULL COMMENT 'Trigger 名称',
    TRIGGER_GROUP VARCHAR(200)   NOT NULL COMMENT 'Trigger 分组',
    STR_PROP_1    VARCHAR(512)   NULL COMMENT '字符串属性 1',
    STR_PROP_2    VARCHAR(512)   NULL COMMENT '字符串属性 2',
    STR_PROP_3    VARCHAR(512)   NULL COMMENT '字符串属性 3',
    INT_PROP_1    INT            NULL COMMENT '整型属性 1',
    INT_PROP_2    INT            NULL COMMENT '整型属性 2',
    LONG_PROP_1   BIGINT         NULL COMMENT '长整型属性 1',
    LONG_PROP_2   BIGINT         NULL COMMENT '长整型属性 2',
    DEC_PROP_1    NUMERIC(13, 4) NULL COMMENT '小数属性 1',
    DEC_PROP_2    NUMERIC(13, 4) NULL COMMENT '小数属性 2',
    BOOL_PROP_1   VARCHAR(1)     NULL COMMENT '布尔属性 1',
    BOOL_PROP_2   VARCHAR(1)     NULL COMMENT '布尔属性 2',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz 属性 Trigger 表';

CREATE TABLE QRTZ_BLOB_TRIGGERS
(
    SCHED_NAME    VARCHAR(120) NOT NULL COMMENT 'Scheduler 名称',
    TRIGGER_NAME  VARCHAR(200) NOT NULL COMMENT 'Trigger 名称',
    TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT 'Trigger 分组',
    BLOB_DATA     BLOB         NULL COMMENT '二进制 Trigger 数据',
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz Blob Trigger 表';

CREATE TABLE QRTZ_CALENDARS
(
    SCHED_NAME    VARCHAR(120) NOT NULL COMMENT 'Scheduler 名称',
    CALENDAR_NAME VARCHAR(200) NOT NULL COMMENT '日历名称',
    CALENDAR      BLOB         NOT NULL COMMENT '日历二进制数据',
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz 日历表';

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS
(
    SCHED_NAME    VARCHAR(120) NOT NULL COMMENT 'Scheduler 名称',
    TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '已暂停 Trigger 分组',
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz 暂停 Trigger 分组表';

CREATE TABLE QRTZ_FIRED_TRIGGERS
(
    SCHED_NAME        VARCHAR(120) NOT NULL COMMENT 'Scheduler 名称',
    ENTRY_ID          VARCHAR(95)  NOT NULL COMMENT '触发记录 ID',
    TRIGGER_NAME      VARCHAR(200) NOT NULL COMMENT 'Trigger 名称',
    TRIGGER_GROUP     VARCHAR(200) NOT NULL COMMENT 'Trigger 分组',
    INSTANCE_NAME     VARCHAR(200) NOT NULL COMMENT 'Scheduler 实例名称',
    FIRED_TIME        BIGINT(13)   NOT NULL COMMENT '实际触发时间戳',
    SCHED_TIME        BIGINT(13)   NOT NULL COMMENT '计划触发时间戳',
    PRIORITY          INTEGER      NOT NULL COMMENT '优先级',
    STATE             VARCHAR(16)  NOT NULL COMMENT '触发状态',
    JOB_NAME          VARCHAR(200) NULL COMMENT 'Job 名称',
    JOB_GROUP         VARCHAR(200) NULL COMMENT 'Job 分组',
    IS_NONCONCURRENT  VARCHAR(1)   NULL COMMENT '是否禁止并发',
    REQUESTS_RECOVERY VARCHAR(1)   NULL COMMENT '是否请求恢复',
    PRIMARY KEY (SCHED_NAME, ENTRY_ID),
    KEY IDX_QRTZ_FT_TRIG_INST_NAME (SCHED_NAME, INSTANCE_NAME),
    KEY IDX_QRTZ_FT_INST_JOB_REQ_RCVRY (SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY),
    KEY IDX_QRTZ_FT_J_G (SCHED_NAME, JOB_NAME, JOB_GROUP),
    KEY IDX_QRTZ_FT_JG (SCHED_NAME, JOB_GROUP),
    KEY IDX_QRTZ_FT_T_G (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    KEY IDX_QRTZ_FT_TG (SCHED_NAME, TRIGGER_GROUP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz 已触发 Trigger 表';

CREATE TABLE QRTZ_SCHEDULER_STATE
(
    SCHED_NAME        VARCHAR(120) NOT NULL COMMENT 'Scheduler 名称',
    INSTANCE_NAME     VARCHAR(200) NOT NULL COMMENT 'Scheduler 实例名称',
    LAST_CHECKIN_TIME BIGINT(13)   NOT NULL COMMENT '最近检入时间戳',
    CHECKIN_INTERVAL  BIGINT(13)   NOT NULL COMMENT '检入间隔毫秒数',
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz 集群实例状态表';

CREATE TABLE QRTZ_LOCKS
(
    SCHED_NAME VARCHAR(120) NOT NULL COMMENT 'Scheduler 名称',
    LOCK_NAME  VARCHAR(40)  NOT NULL COMMENT '锁名称',
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Quartz 集群锁表';

ALTER TABLE QRTZ_TRIGGERS
    ADD CONSTRAINT QRTZ_TRIGGERS_JOB_DETAILS_FK
        FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
            REFERENCES QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP);

ALTER TABLE QRTZ_SIMPLE_TRIGGERS
    ADD CONSTRAINT QRTZ_SIMPLE_TRIGGERS_TRIGGERS_FK
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            ON DELETE CASCADE;

ALTER TABLE QRTZ_CRON_TRIGGERS
    ADD CONSTRAINT QRTZ_CRON_TRIGGERS_TRIGGERS_FK
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            ON DELETE CASCADE;

ALTER TABLE QRTZ_SIMPROP_TRIGGERS
    ADD CONSTRAINT QRTZ_SIMPROP_TRIGGERS_TRIGGERS_FK
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            ON DELETE CASCADE;

ALTER TABLE QRTZ_BLOB_TRIGGERS
    ADD CONSTRAINT QRTZ_BLOB_TRIGGERS_TRIGGERS_FK
        FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            REFERENCES QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            ON DELETE CASCADE;

INSERT IGNORE INTO QRTZ_LOCKS (SCHED_NAME, LOCK_NAME)
VALUES ('peachScheduler', 'TRIGGER_ACCESS'),
       ('peachScheduler', 'JOB_ACCESS'),
       ('peachScheduler', 'CALENDAR_ACCESS'),
       ('peachScheduler', 'STATE_ACCESS'),
       ('peachScheduler', 'MISFIRE_ACCESS');
