-- 用户操作日志表
CREATE TABLE USER_OPER_LOG (
    ID VARCHAR(32) NOT NULL COMMENT '主键',
    OPT_TYPE_CODE VARCHAR(50) COMMENT '操作类型编码',
    MODULE_CODE VARCHAR(50) COMMENT '模块编码',
    CREATOR_CODE VARCHAR(50) COMMENT '创建人编码',
    CREATOR_NAME VARCHAR(100) COMMENT '创建人名称',
    OPT_CONTENT VARCHAR(4000) COMMENT '操作内容',
    CREATE_TIME VARCHAR(20) COMMENT '创建时间',
    OPT_LEVEL VARCHAR(10) COMMENT '操作级别',
    PRIVATE_IP VARCHAR(50) COMMENT '私网IP',
    PUBLIC_IP VARCHAR(50) COMMENT '公网IP',
    DEVICE VARCHAR(200) COMMENT '设备信息',
    BROWSER VARCHAR(200) COMMENT '浏览器信息',
    OS VARCHAR(100) COMMENT '操作系统',
    EXECUTION_TIME BIGINT COMMENT '执行时间（毫秒）',
    IS_SUCCESS VARCHAR(4) COMMENT '是否成功 (Y: 成功, N: 失败)',
    ERROR_MSG VARCHAR(2000) COMMENT '错误信息',
    RESPONSE_DATA TEXT COMMENT '响应数据',
    ROLE_CODE VARCHAR(50) COMMENT '角色编码',
    REQUEST_URI VARCHAR(500) COMMENT '请求路径',
    REQUEST_METHOD VARCHAR(10) COMMENT '请求方式',
    PRIMARY KEY (ID)
) COMMENT='用户操作日志表';